---
- name: Validate that we have a download_folder
  fail:
    msg: "Please specify a local download folder: -e download_folder=<local download folder>"
  when: download_folder is not defined

- name: Examine download_set passed in
  debug:
    var: "{{ download_set }}"

- name: Download files
  fetch:
    src: "{{ item.path }}"
    dest: "{{ download_folder }}"
  with_items: "{{ download_set.files }}"
  when: download_set.files | length > 0
