---
- name: Validate that we have a download_folder
  fail:
    msg: "Please specify a local download folder: -e download_folder=<local download folder>"
  when: download_folder is not defined

- name: Download files
  include: download_file.yml
  with_items: "{{ result.files }}"
  loop_control:
    loop_var: file

