---
# tasks file for fetch-found-files
- name: Validate that we have download_pattern
  fail:
    msg: "Please provide a download_pattern list that follows dir: 'directory name', pattern: 'file pattern'"
  when: download_pattern is not defined

#- name: Create download folder
#  local_action: file path={{ download_folder }} state=directory

- name: Find download log files
  find:
    path: '{{ item.dir }}'
    pattern: '{{ item.pattern }}'
    file_type: file
    recurse: yes
  with_items: "{{ download_pattern }}"
  register: downloads

- name: Download log files found
  debug:
    var: downloads

- name: Download.results log files found
  debug:
    var: downloads.results

- name: Iterate over download.results
  debug:
    var: "{{ item }}"
  with_items: downloads.results

#- name: Iterate over patterns found
#  include: download_files.yml
#  loop_control:
#    loop_var: result
#  with_items: '{{ downloads.results }}'
