---
# tasks file for fetch-found-files
- name: Validate that we a download_folder
  fail:
    msg: "Please specify a local download folder: -e download_folder=<local download folder>"
  when: download_folder is not defined

- name: Validate that we have download_patterns
  fail:
    msg: "Please provide a download pattern list that follows dir: 'directory name', pattern: 'file pattern'"
  when: download_patterns is not defined

- name: Create download folder
  local_action: file path={{ download_folder }} state=directory

- name: Find download log files
  find:
    path: '{{ item.dir }}'
    pattern: '{{ item.pattern }}'
    file_type: file
    recurse: yes
  register: downloads
  with_items: "{{ download_patterns }}"

- name: Iterate over patterns found
  include: download_patterns.yml
  loop_control:
    loop_var: result_files
  with_items: '{{ downloads.results }}'
