---
# tasks file for fetch-found-files

- name: Listing of fetch_files criteria
  debug:
    var: fetch_files

- name: Use find to search for files to download
  shell: "find {{ item.dir }} -type f -name '{{ item.name }}'"
  register: logs
  with_items: '{{ fetch_files }}'
  ignore_errors: yes

- name: Fetch_files found for downloading
  debug:
    var: logs.results.stdout_lines

- include: fetch_files.yml
  with_items:
  - '{{ logs.results.stdout_lines }}'
  loop_control:
    loop_var: result

