---
# tasks file for fetch-found-files

- name: Use find to search for files to download
  shell: "find {{ item.dir }} -type f -name '{{ item.name }}'"
  register: logs
  with_items: '{{ fetch_files }}'
  ignore_errors: yes

- include: fetch_files.yml
  with_items:
  - '{{ logs.results }}'
  loop_control:
    loop_var: result

